github:
	rst2html5.py github-tut.rst > github-tut.html && firefox github-tut.html

tortoise:
	rst2html5.py tortoiseGit-tut.rst > tortoiseGit-tut.html && firefox tortoiseGit-tut.html

clean:
	rm -rf *.html

